os:
- linux
sudo: true
language:
- c
before_install:
  - sudo apt-get install -y cmake libapr1-dev libaprutil1-dev doxygen
before_script:
- wget https://github.com/orpiske/gru/tarball/master -O gru-head.tar.gz
- mkdir gru && tar -xvf gru-head.tar.gz -C gru --strip-components=1
- cd gru && mkdir build && cmake .. && make && make install
- mkdir build
- cd build
- cmake -DCMAKE_BUILD_TYPE=RELEASE -DSTOMP_SUPPORT=OFF -DAMQP_SUPPORT=OFF ..
script:
- make all
