nv:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "UG9bN27ka6l8QOQ7sATB/l8DuNFx22Sat6w45kmHlbQXKdH6FPqLbsV5XXTzpKvoUSGH/oGHHWfna/SnzI+6BTUQQTPNKXDV3JGU3PAMZIw4Va/1WOb7S3Bu1djzQpofG/0iJKb2maGQIRzogg33YiD8VLYwiXyayWvm6hQgr4r6NsckmJRJuqy5xotHI8L7CuUX2PT7JLRZTDR1X2yE4yv39Uvj1FZFNRD7WYa+Qp92ewWv/le9qP64heCh5gMSqOM9CozIjb4RtBnpJ6qBUVuQq2WdmmeO0YjkvXChT3gb1syr/hrhANK/W9sB08+La3OeP9loNZMwhutoCu8uTY4cgtbLxs2DI0xKCCzOqoJamf21M/BlQh8SK+5OqIRHM6h2/o4+wazuYT0sWeAbIFtBuJVG1Smaqtxqf03K6EnpjCGUt+5F/FHrSAE4AmsFiqmk9ItyrgZ4gcKPH7T61berjRrFGsrzC7hUK+ZHsqxvrMq00rfZEH9WT71yd1RFLI7Oz9VzeVqC860L6BiFH+Z+YLaTahDWURNF2BAv4JtLrJropR1ITweLNnpEolCSHr0Wa+TkTmKsYvu2vLyjC7dvDxnXVpYdCnTN+DfMls9vRLgNlEBJ6iWPKcGWgzSc1VSkOy2XDwB4y2xcNpRAyXvZakdJnRB2PRZCY6AMkdQ="

os:
  - linux
  - osx
dist: trusty
sudo: true
language:
  - c
before_install:
  - ./travis-builder.sh before_install
before_script:
  - ./travis-builder.sh before_script
script:
  - ./travis-builder.sh build
addons:
  apt:
    packages:
      - zlib1g-dev
      - libapr1-dev
      - libaprutil1-dev
      - liburiparser-dev
      - libjson0-dev
      - libcurl4-openssl-dev
      - libreadline6
      - libreadline6-dev
      - uuid-dev
      - doxygen
      - build-essential
      - libssl-dev
  coverity_scan:
    project:
      name: "orpiske/msg-perf-tool"
      description: "Messaging performance test tool"
    notification_email: angusyoung@gmail.com
    build_command_prepend: "mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=RELEASE -DMQTT_SUPPORT=ON -DSTOMP_SUPPORT=ON -DAMQP_SUPPORT=OFF .."
    build_command: "make all"
    branch_pattern: coverity_scan
