env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "JaQw0vm0WIswdPRgoNYMpxGP17xcylvEnOxmqiGUckU75Ky767wRpufJ5ZipBd2W4oRVPuZVaDBXiJ7WA7A1uLeW0/VHcKmmag6EcrHkHM6Sg8lMlo2A336PtfbFyUCiOqYMHZPpFRK0bq+oM/q1+iZJywDjnziMRLoSBcY/Rxd19fFAKgfT2iO7EaTqBh1QfOyXJGbvjicfEp5kcLE6BkaRmuYqu717R6i2vmyd3Rg6ICoHL80NGDX5jMb7aFzzWR78ywWfqvDY2nWkwALDMu9nqrU5QWW6BkCId6Q8GZJyM/t0DC5BViCc8ZnTRDm/HrZ4kI+dz/zH+8VbQ6TprV/zL69dyX1GJogLZ6bCGNNhDV4GeERfaOeNGwCzRkaiAmqCPpgIUhIcuNuVSexLFq5hcHhhkMKGugVMVNg5AUT0K4fg1XwRio3y6CQDbQx3oE4xFryc8XuSIsBmJU0CBD8O1sl+SXqG8rWO5lDExTeeR2lfDr4+xnSIV21UFbFG8gcRz6bx0Uzemj85ah+koGBvnUpKo8K5lNtlDk/5MYchqQEWvhDX7zbJ7gJJ13aOx8lymM0e3/Too0FWGkumDHifhUo/LxL5Rk11T2igRRfTq6IEE7Iy0adf03Z4r0GagRVLj2iC7OmHfO61RyvNFKdL+xP4qotmjDcfSf0Fegg="

os:
  - linux
  - osx
dist: trusty
sudo: true
language:
  - c
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; brew install uriparser json-c ossp-uuid msgpack; fi

before_script:
  - echo "Installing gru"
  - wget https://github.com/orpiske/gru/tarball/master -O gru-head.tar.gz
  - mkdir gru && tar -xvf gru-head.tar.gz -C gru --strip-components=1
  - pushd gru && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=DEBUG .. && make && sudo make install ; popd
  - wget https://github.com/orpiske/litestomp/tarball/master -O litestomp-head.tar.gz
  - echo "Installing bmic"
  - wget https://github.com/orpiske/bmic/tarball/master -O bmic-head.tar.gz
  - mkdir bmic && tar -xvf bmic-head.tar.gz -C bmic --strip-components=1
  - pushd bmic && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=DEBUG .. && make && sudo make install ; popd
  - echo "Installing litestomp"
  - mkdir litestomp && tar -xvf litestomp-head.tar.gz -C litestomp --strip-components=1
  - pushd litestomp && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=DEBUG .. && make && sudo make install ; popd
  - echo "Installing Paho MQTT C"
  - wget https://github.com/eclipse/paho.mqtt.c/tarball/master -O pahoc-head.tar.gz
  - mkdir pahoc && tar -xvf pahoc-head.tar.gz -C pahoc --strip-components=1
  - pushd pahoc && mkdir build.paho && cd build.paho && cmake -DPAHO_WITH_SSL=FALSE -DPAHO_BUILD_SAMPLES=FALSE -DPAHO_BUILD_DOCUMENTATION=FALSE -DCMAKE_BUILD_TYPE=RELEASE .. && make && sudo make install ; popd
script:
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=DEBUG -DSTOMP_SUPPORT=OFF -DAMQP_SUPPORT=OFF ..
  - make all
  - cd ..
addons:
  apt:
    packages:
      - libapr1-dev
      - libaprutil1-dev
      - liburiparser-dev
      - libjson0-dev
      - libcurl4-openssl-dev
      - libmsgpack-dev
      - uuid-dev
      - doxygen
  coverity_scan:
    project:
      name: "orpiske/msg-perf-tool"
      description: "Messaging performance test tool"
    notification_email: angusyoung@gmail.com
    build_command_prepend: "mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=RELEASE -DSTOMP_SUPPORT=ON -DAMQP_SUPPORT=OFF .."
    build_command: "make all"
    branch_pattern: coverity_scan
